#!/usr/bin/env python3
"""Generate judge/BURNDOWN.md: per-gen-file pass/fail counts under rtcl,
plus failure clustering by command under test.

Usage: python3 judge/extract/burndown.py
"""
import json
import os
import re
import subprocess
from collections import Counter, defaultdict

ROOT = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
GEN = os.path.join(ROOT, "judge", "corpus", "gen")
STATS = os.path.join(ROOT, "judge", "extract", "stats.json")
OUT = os.path.join(ROOT, "judge", "BURNDOWN.md")
RTCL = os.path.join(ROOT, "target", "release", "rtcl")

CASE_RE = re.compile(r"^# case: (\S+) cmd=(.*)$", re.M)

def parse_cases(path):
    with open(path, encoding="utf-8", errors="surrogateescape") as f:
        text = f.read()
    return [(m.group(1), m.group(2)) for m in CASE_RE.finditer(text)]

def run_rtcl(path):
    try:
        p = subprocess.run([RTCL, "-f", path], capture_output=True, timeout=20)
        return p.returncode, p.stdout.decode("utf-8", errors="surrogateescape")
    except subprocess.TimeoutExpired:
        return 124, ""

def main():
    with open(STATS) as f:
        stats = json.load(f)
    rows = []
    clusters = defaultdict(list)  # cmd -> [(file, case)]
    tot_pass = tot_fail = tot_died = tot_cases = 0
    for fname in sorted(os.listdir(GEN)):
        if not fname.endswith(".tcl"):
            continue
        base = fname[:-4]
        path = os.path.join(GEN, fname)
        cases = parse_cases(path)
        code, out = run_rtcl(path)
        lines = out.split("\n")
        passed, failed = [], []
        seen = 0
        for i, (name, cmd) in enumerate(cases):
            line = lines[i] if i < len(lines) else None
            if line == "PASS":
                passed.append(name)
            elif line == "FAIL " + name:
                failed.append((name, cmd))
            else:
                break
            seen = i + 1
        died = len(cases) - seen
        died_names = [c[0] for c in cases[seen:]]
        for name, cmd in failed:
            clusters[cmd].append((base, name))
        if died and died_names:
            clusters["(died: crash/hang)"].append((base, died_names[0]))
        rows.append((base, len(cases), len(passed), len(failed), died, code))
        tot_cases += len(cases); tot_pass += len(passed)
        tot_fail += len(failed); tot_died += died

    pct = (100.0 * tot_pass / tot_cases) if tot_cases else 0.0
    lines = []
    lines.append("# Judge burndown -- official Tcl test suite extraction\n")
    lines.append("Oracle: tclsh 8.6.17. Candidate: rtcl. Generated by "
                 "`judge/extract/extract.py` + `burndown.py`.\n")
    lines.append("## Extraction funnel\n")
    t = stats["total"]
    funnel = [
        ("test commands found in .refer/tcl/tests", t.get("found", 0)),
        ("skipped: unparseable command", t.get("unparseable-cmd", 0)),
        ("skipped: unsupported shape", t.get("skip-shape", 0)),
        ("skipped: -constraints", t.get("skip-opt-constraints", 0)),
        ("skipped: -setup", t.get("skip-opt-setup", 0)),
        ("skipped: -cleanup", t.get("skip-opt-cleanup", 0)),
        ("skipped: -match glob/regexp", t.get("skip-opt-match", 0)),
        ("skipped: -returnCodes other", t.get("skip-returncodes", 0)),
        ("skipped: body/result substitution", t.get("skip-body-subst", 0) + t.get("skip-result-subst", 0)),
        ("skipped: blacklist (IO/clock/env/...)", t.get("skip-blacklist", 0)),
        ("skipped: other options/names", sum(v for k, v in t.items()
            if k.startswith("skip-") and k not in
            {"skip-shape", "skip-opt-constraints", "skip-opt-setup",
             "skip-opt-cleanup", "skip-opt-match", "skip-returncodes",
             "skip-body-subst", "skip-result-subst", "skip-blacklist"})),
        ("extracted candidates", t.get("extracted", 0)),
        ("dropped by tclsh self-verification", t.get("verify-dropped", 0)),
        ("kept in corpus (tclsh prints PASS)", t.get("kept", 0)),
    ]
    for label, n in funnel:
        lines.append("- %s: %d" % (label, n))
    lines.append("")
    lines.append("## rtcl vs oracle: %d/%d cases pass (%.1f%%)\n"
                 % (tot_pass, tot_cases, pct))
    lines.append("| gen file | cases | pass | fail | died | rtcl exit |")
    lines.append("|---|---|---|---|---|---|")
    for base, n, p, fl, d, code in rows:
        flag = "ok" if code == 0 else ("**hang/crash (%d)**" % code)
        lines.append("| %s | %d | %d | %d | %d | %s |"
                     % (base, n, p, fl, d, flag))
    lines.append("| **total** | **%d** | **%d** | **%d** | **%d** | |"
                 % (tot_cases, tot_pass, tot_fail, tot_died))
    lines.append("")
    lines.append("## Failure clusters (by command under test)\n")
    lines.append("| cluster | count | representative case |")
    lines.append("|---|---|---|")
    for cmd, items in sorted(clusters.items(), key=lambda kv: -len(kv[1])):
        rep = "%s:%s" % items[0]
        lines.append("| %s | %d | %s |" % (cmd.replace("|", "\\|"),
                                           len(items), rep))
    lines.append("")
    with open(OUT, "w") as f:
        f.write("\n".join(lines))
    print("wrote %s" % OUT)
    print("pass %d/%d (%.1f%%)  fail=%d died=%d" %
          (tot_pass, tot_cases, pct, tot_fail, tot_died))
    print("top clusters:")
    for cmd, items in sorted(clusters.items(), key=lambda kv: -len(kv[1]))[:10]:
        print("  %-28s %4d  e.g. %s:%s" % (cmd, len(items), *items[0]))

if __name__ == "__main__":
    main()
