# generated by judge/extract/extract.py -- do not edit
# case: trace-0.0 cmd=?
set __judge_c [catch {
    # You may need Purify or Electric Fence to reliably
    # see this one fail.
    unset -nocomplain z
    trace add variable z array {set z(foo) 1 ;#}
    set res "names: [array names z]"
    unset -nocomplain ::z
    trace add variable ::z write {unset ::z; error "memory corruption";#}
    list [catch {set ::z 1} msg] $msg
} __judge_r]
if {$__judge_c == 0 && $__judge_r eq {1 {can't set "::z": memory corruption}}} {puts PASS} else {puts "FAIL trace-0.0"}
# case: trace-1.1 cmd=unset
set __judge_c [catch {
    unset -nocomplain x
    set info {}
    trace add variable x read traceScalar
    list [catch {set x} msg] $msg $info
} __judge_r]
if {$__judge_c == 0 && $__judge_r eq {1 {can't read "x": no such variable} {x {} read 1 {can't read "x": no such variable}}}} {puts PASS} else {puts "FAIL trace-1.1"}
# case: trace-1.2 cmd=unset
set __judge_c [catch {
    unset -nocomplain x
    set x 123
    set info {}
    trace add variable x read traceScalar
    list [catch {set x} msg] $msg $info
} __judge_r]
if {$__judge_c == 0 && $__judge_r eq {0 123 {x {} read 0 123}}} {puts PASS} else {puts "FAIL trace-1.2"}
# case: trace-1.3 cmd=unset
set __judge_c [catch {
    unset -nocomplain x
    set info {}
    trace add variable x read traceScalar
    set x 123
    set info
} __judge_r]
if {$__judge_c == 0 && $__judge_r eq {}} {puts PASS} else {puts "FAIL trace-1.3"}
# case: trace-1.4 cmd=unset
set __judge_c [catch {
    unset -nocomplain x
    set info {}
    trace add variable x(2) read traceArray
    list [catch {set x(2)} msg] $msg $info
} __judge_r]
if {$__judge_c == 0 && $__judge_r eq {1 {can't read "x(2)": no such element in array} {x 2 read 1 {can't read "x(2)": no such element in array}}}} {puts PASS} else {puts "FAIL trace-1.4"}
# case: trace-1.5 cmd=unset
set __judge_c [catch {
    unset -nocomplain x
    set x(2) zzz
    set info {}
    trace add variable x(2) read traceArray
    list [catch {set x(2)} msg] $msg $info
} __judge_r]
if {$__judge_c == 0 && $__judge_r eq {0 zzz {x 2 read 0 zzz}}} {puts PASS} else {puts "FAIL trace-1.5"}
# case: trace-1.6 cmd=unset
set __judge_c [catch {
    unset -nocomplain x
    set info {}
    trace add variable x read traceArray2
    proc p {} {
	global x
	set x(2) willi
	return $x(2)
    }
    list [catch {p} msg] $msg $info
} __judge_r]
if {$__judge_c == 0 && $__judge_r eq {0 willi {x 2 read}}} {puts PASS} else {puts "FAIL trace-1.6"}
# case: trace-1.7 cmd=unset
set __judge_c [catch {
    unset -nocomplain x
    set info {}
    trace add variable x read q
    proc q {name1 name2 op} {
	global info
	set info [list $name1 $name2 $op]
	global $name1
	set ${name1}($name2) wolf
    }
    proc p {} {
	global x
	set x(X) willi
	return $x(Y)
    }
    list [catch {p} msg] $msg $info
} __judge_r]
if {$__judge_c == 0 && $__judge_r eq {0 wolf {x Y read}}} {puts PASS} else {puts "FAIL trace-1.7"}
# case: trace-1.8 cmd=unset
set __judge_c [catch {
    unset -nocomplain x
    set info {}
    trace add variable x read traceArray
    list [catch {set x(2)} msg] $msg $info
} __judge_r]
if {$__judge_c == 0 && $__judge_r eq {1 {can't read "x(2)": no such variable} {}}} {puts PASS} else {puts "FAIL trace-1.8"}
# case: trace-1.9 cmd=unset
set __judge_c [catch {
    unset -nocomplain x
    set x(2) zzz
    set info {}
    trace add variable x read traceArray
    list [catch {set x(2)} msg] $msg $info
} __judge_r]
if {$__judge_c == 0 && $__judge_r eq {0 zzz {x 2 read 0 zzz}}} {puts PASS} else {puts "FAIL trace-1.9"}
# case: trace-1.10 cmd=unset
set __judge_c [catch {
    unset -nocomplain x
    set x 444
    set info {}
    trace add variable x read traceScalar
    unset x
    set info
} __judge_r]
if {$__judge_c == 0 && $__judge_r eq {}} {puts PASS} else {puts "FAIL trace-1.10"}
# case: trace-1.11 cmd=unset
set __judge_c [catch {
    unset -nocomplain x
    set x(bar) 0
    trace add variable x read {set x(foo) 1 ;#}
    trace add variable x read {unset -nocomplain x(bar) ;#}
    array get x
} __judge_r]
if {$__judge_c == 0 && $__judge_r eq {}} {puts PASS} else {puts "FAIL trace-1.11"}
# case: trace-1.12 cmd=unset
set __judge_c [catch {
    unset -nocomplain x
    set x(bar) 0
    trace add variable x read {unset -nocomplain x(bar) ;#}
    trace add variable x read {set x(foo) 1 ;#}
    array get x
} __judge_r]
if {$__judge_c == 0 && $__judge_r eq {}} {puts PASS} else {puts "FAIL trace-1.12"}
# case: trace-1.13 cmd=unset
set __judge_c [catch {
    unset -nocomplain x
    set x(bar) 0
    trace add variable x read {set x(foo) 1 ;#}
    trace add variable x read {unset -nocomplain x;#}
    list [catch {array get x} res] $res
} __judge_r]
if {$__judge_c == 0 && $__judge_r eq {1 {can't read "x(bar)": no such variable}}} {puts PASS} else {puts "FAIL trace-1.13"}
# case: trace-1.14 cmd=unset
set __judge_c [catch {
    unset -nocomplain x
    set x(bar) 0
    trace add variable x read {unset -nocomplain x;#}
    trace add variable x read {set x(foo) 1 ;#}
    list [catch {array get x} res] $res
} __judge_r]
if {$__judge_c == 0 && $__judge_r eq {1 {can't read "x(bar)": no such variable}}} {puts PASS} else {puts "FAIL trace-1.14"}
# case: trace-2.1 cmd=unset
set __judge_c [catch {
    unset -nocomplain x
    set info {}
    trace add variable x write traceScalar
    set x 123
    set info
} __judge_r]
if {$__judge_c == 0 && $__judge_r eq {x {} write 0 123}} {puts PASS} else {puts "FAIL trace-2.1"}
# case: trace-2.2 cmd=unset
set __judge_c [catch {
    unset -nocomplain x
    set info {}
    trace add variable x(33) write traceArray
    set x(33) 444
    set info
} __judge_r]
if {$__judge_c == 0 && $__judge_r eq {x 33 write 0 444}} {puts PASS} else {puts "FAIL trace-2.2"}
# case: trace-2.3 cmd=unset
set __judge_c [catch {
    unset -nocomplain x
    set info {}
    trace add variable x write traceArray
    set x(abc) qq
    set info
} __judge_r]
if {$__judge_c == 0 && $__judge_r eq {x abc write 0 qq}} {puts PASS} else {puts "FAIL trace-2.3"}
# case: trace-2.4 cmd=unset
set __judge_c [catch {
    unset -nocomplain x
    set x 1234
    set info {}
    trace add variable x write traceScalar
    set x
    set info
} __judge_r]
if {$__judge_c == 0 && $__judge_r eq {}} {puts PASS} else {puts "FAIL trace-2.4"}
# case: trace-2.5 cmd=unset
set __judge_c [catch {
    unset -nocomplain x
    set x 1234
    set info {}
    trace add variable x write traceScalar
    unset x
    set info
} __judge_r]
if {$__judge_c == 0 && $__judge_r eq {}} {puts PASS} else {puts "FAIL trace-2.5"}
# case: trace-2.6 cmd=?
set __judge_c [catch {
    #
    # Check correct function of whole array traces on compiled local
    # arrays [Bug 1770591]. The corresponding function for read traces is
    # already indirectly tested in trace-1.7
    #
    unset -nocomplain x
    set info {}
    proc p {} {
	trace add variable x write traceArray
	set x(X) willy
    }
    p
    set info
} __judge_r]
if {$__judge_c == 0 && $__judge_r eq {x X write 0 willy}} {puts PASS} else {puts "FAIL trace-2.6"}
# case: trace-3.1 cmd=unset
set __judge_c [catch {
    unset -nocomplain x
    set info {}
    trace add variable x read traceScalarAppend
    append x 123
    append x 456
    lappend x 789
    set info
} __judge_r]
if {$__judge_c == 0 && $__judge_r eq {x {} read 0 123456}} {puts PASS} else {puts "FAIL trace-3.1"}
# case: trace-4.1 cmd=unset
set __judge_c [catch {
    unset -nocomplain x
    set info {}
    trace add variable x unset traceScalar
    unset -nocomplain x
    set info
} __judge_r]
if {$__judge_c == 0 && $__judge_r eq {x {} unset 1 {can't read "x": no such variable}}} {puts PASS} else {puts "FAIL trace-4.1"}
# case: trace-4.2 cmd=unset
set __judge_c [catch {
    unset -nocomplain x
    set x 1234
    set info {}
    trace add variable x unset traceScalar
    unset x
    set info
} __judge_r]
if {$__judge_c == 0 && $__judge_r eq {x {} unset 1 {can't read "x": no such variable}}} {puts PASS} else {puts "FAIL trace-4.2"}
# case: trace-4.3 cmd=unset
set __judge_c [catch {
    unset -nocomplain x
    set info {}
    trace add variable x unset traceScalar
    set x 44
    set x
    set info
} __judge_r]
if {$__judge_c == 0 && $__judge_r eq {}} {puts PASS} else {puts "FAIL trace-4.3"}
# case: trace-4.4 cmd=unset
set __judge_c [catch {
    unset -nocomplain x
    set x(0) 18
    set info {}
    trace add variable x(1) unset traceArray
    unset -nocomplain x(1)
    set info
} __judge_r]
if {$__judge_c == 0 && $__judge_r eq {x 1 unset 1 {can't read "x(1)": no such element in array}}} {puts PASS} else {puts "FAIL trace-4.4"}
# case: trace-4.5 cmd=unset
set __judge_c [catch {
    unset -nocomplain x
    set x(1) 18
    set info {}
    trace add variable x(1) unset traceArray
    unset x(1)
    set info
} __judge_r]
if {$__judge_c == 0 && $__judge_r eq {x 1 unset 1 {can't read "x(1)": no such element in array}}} {puts PASS} else {puts "FAIL trace-4.5"}
# case: trace-4.6 cmd=unset
set __judge_c [catch {
    unset -nocomplain x
    set x(1) 18
    set info {}
    trace add variable x(1) unset traceArray
    unset x
    set info
} __judge_r]
if {$__judge_c == 0 && $__judge_r eq {x 1 unset 1 {can't read "x(1)": no such variable}}} {puts PASS} else {puts "FAIL trace-4.6"}
# case: trace-4.7 cmd=unset
set __judge_c [catch {
    unset -nocomplain x
    set x(1) 18
    set info {}
    trace add variable x unset traceProc
    unset -nocomplain x(0)
    set info
} __judge_r]
if {$__judge_c == 0 && $__judge_r eq {}} {puts PASS} else {puts "FAIL trace-4.7"}
# case: trace-4.8 cmd=unset
set __judge_c [catch {
    unset -nocomplain x
    set x(1) 18
    set x(2) 144
    set x(3) 14
    set info {}
    trace add variable x unset traceProc
    unset x(1)
    set info
} __judge_r]
if {$__judge_c == 0 && $__judge_r eq {x 1 unset}} {puts PASS} else {puts "FAIL trace-4.8"}
# case: trace-4.9 cmd=unset
set __judge_c [catch {
    unset -nocomplain x
    set x(1) 18
    set x(2) 144
    set x(3) 14
    set info {}
    trace add variable x unset traceProc
    unset x
    set info
} __judge_r]
if {$__judge_c == 0 && $__judge_r eq {x {} unset}} {puts PASS} else {puts "FAIL trace-4.9"}
# case: trace-5.1 cmd=unset
set __judge_c [catch {
    unset -nocomplain x
    set x(b) 2
    trace add variable x array traceArray2
    set ::info {}
    array set x {a 1}
    set ::info
} __judge_r]
if {$__judge_c == 0 && $__judge_r eq {x {} array}} {puts PASS} else {puts "FAIL trace-5.1"}
# case: trace-5.2 cmd=unset
set __judge_c [catch {
    unset -nocomplain x
    set x(b) 2
    trace add variable x array traceArray2
    set ::info {}
    set x(a) 1
    set x(b) $x(a)
    set ::info
} __judge_r]
if {$__judge_c == 0 && $__judge_r eq {}} {puts PASS} else {puts "FAIL trace-5.2"}
# case: trace-5.3 cmd=unset
set __judge_c [catch {
    unset -nocomplain x
    trace add variable x array traceArray2
    set ::info {}
    set x(a) 1
    unset x
    array set x {a 1}
    set ::info
} __judge_r]
if {$__judge_c == 0 && $__judge_r eq {}} {puts PASS} else {puts "FAIL trace-5.3"}
# case: trace-5.6 cmd=unset
set __judge_c [catch {
    unset -nocomplain x
    set x foo
    trace add variable x array traceArray2
    set ::info {}
    catch {array set x {a 1}}
    set ::info
} __judge_r]
if {$__judge_c == 0 && $__judge_r eq {}} {puts PASS} else {puts "FAIL trace-5.6"}
# case: trace-5.7 cmd=unset
set __judge_c [catch {
    unset -nocomplain x
    trace add variable x array traceArray2
    set ::info {}
    array set x {a 1}
    set ::info
} __judge_r]
if {$__judge_c == 0 && $__judge_r eq {x {} array}} {puts PASS} else {puts "FAIL trace-5.7"}
# case: trace-5.8 cmd=unset
set __judge_c [catch {
    unset -nocomplain x
    trace add variable x array {set x(foo) 1 ;#}
    set res "names: [array names x]"
} __judge_r]
if {$__judge_c == 0 && $__judge_r eq {names: foo}} {puts PASS} else {puts "FAIL trace-5.8"}
# case: trace-7.1 cmd=unset
set __judge_c [catch {
    unset -nocomplain x
    set info {}
    trace add variable x read "traceTag 1"
    trace add variable x read "traceTag 2"
    trace add variable x read "traceTag 3"
    catch {set x}
    set x 22
    set x
    set info
} __judge_r]
if {$__judge_c == 0 && $__judge_r eq {3 2 1 3 2 1}} {puts PASS} else {puts "FAIL trace-7.1"}
# case: trace-7.2 cmd=unset
set __judge_c [catch {
    unset -nocomplain x
    set x(0) 44
    set info {}
    trace add variable x(0) read "traceTag 1"
    trace add variable x(0) read "traceTag 2"
    trace add variable x(0) read "traceTag 3"
    set x(0)
    set info
} __judge_r]
if {$__judge_c == 0 && $__judge_r eq {3 2 1}} {puts PASS} else {puts "FAIL trace-7.2"}
# case: trace-7.3 cmd=unset
set __judge_c [catch {
    unset -nocomplain x
    set x(0) 44
    set info {}
    trace add variable x(0) read "traceTag 1"
    trace add variable x read "traceTag A1"
    trace add variable x(0) read "traceTag 2"
    trace add variable x read "traceTag A2"
    trace add variable x(0) read "traceTag 3"
    trace add variable x read "traceTag A3"
    set x(0)
    set info
} __judge_r]
if {$__judge_c == 0 && $__judge_r eq {A3 A2 A1 3 2 1}} {puts PASS} else {puts "FAIL trace-7.3"}
# case: trace-8.1 cmd=unset
set __judge_c [catch {
    unset -nocomplain x
    set x 123
    set info {}
    trace add variable x read "traceTag 1"
    trace add variable x read traceError
    list [catch {set x} msg] $msg $info
} __judge_r]
if {$__judge_c == 0 && $__judge_r eq {1 {can't read "x": trace returned error} {}}} {puts PASS} else {puts "FAIL trace-8.1"}
# case: trace-8.2 cmd=unset
set __judge_c [catch {
    unset -nocomplain x
    set x 123
    set info {}
    trace add variable x write "traceTag 1"
    trace add variable x write traceError
    list [catch {set x 44} msg] $msg $info
} __judge_r]
if {$__judge_c == 0 && $__judge_r eq {1 {can't set "x": trace returned error} {}}} {puts PASS} else {puts "FAIL trace-8.2"}
# case: trace-8.3 cmd=unset
set __judge_c [catch {
    unset -nocomplain x
    set x 123
    set info {}
    trace add variable x write traceError
    list [catch {append x 44} msg] $msg $info
} __judge_r]
if {$__judge_c == 0 && $__judge_r eq {1 {can't set "x": trace returned error} {}}} {puts PASS} else {puts "FAIL trace-8.3"}
# case: trace-8.4 cmd=unset
set __judge_c [catch {
    unset -nocomplain x
    set x 123
    set info {}
    trace add variable x unset "traceTag 1"
    trace add variable x unset traceError
    list [catch {unset x} msg] $msg $info
} __judge_r]
if {$__judge_c == 0 && $__judge_r eq {0 {} 1}} {puts PASS} else {puts "FAIL trace-8.4"}
# case: trace-8.5 cmd=unset
set __judge_c [catch {
    unset -nocomplain x
    set x(0) 123
    set info {}
    trace add variable x(0) read "traceTag 1"
    trace add variable x read "traceTag 2"
    trace add variable x read traceError
    trace add variable x read "traceTag 3"
    list [catch {set x(0)} msg] $msg $info
} __judge_r]
if {$__judge_c == 0 && $__judge_r eq {1 {can't read "x(0)": trace returned error} 3}} {puts PASS} else {puts "FAIL trace-8.5"}
# case: trace-8.6 cmd=unset
set __judge_c [catch {
    unset -nocomplain x
    set x 123
    trace add variable x unset traceError
    list [catch {unset x} msg] $msg
} __judge_r]
if {$__judge_c == 0 && $__judge_r eq {0 {}}} {puts PASS} else {puts "FAIL trace-8.6"}
# case: trace-8.7 cmd=?
set __judge_c [catch {
    # This test just makes sure that the memory for the error message
    # gets deallocated correctly when the trace is invoked again or
    # when the trace is deleted.
    unset -nocomplain x
    set x 123
    trace add variable x read traceError
    catch {set x}
    catch {set x}
    trace remove variable x read traceError
} __judge_r]
if {$__judge_c == 0 && $__judge_r eq {}} {puts PASS} else {puts "FAIL trace-8.7"}
# case: trace-8.8 cmd=?
set __judge_c [catch {
    # Yet more elaborate memory corruption testing that checks nothing
    # bad happens when the trace deletes itself and installs something
    # new.  Alas, there is no neat way to guarantee that this test will
    # fail if there is a problem, but that's life and with the new code
    # it should *never* fail.
    #
    # Adapted from Bug #219393 reported by Don Porter.
    catch {rename ::foo {}}
    proc foo {old args} {
	trace remove variable ::x write [list foo $old]
	trace add    variable ::x write [list foo $::x]
	error "foo"
    }
    unset -nocomplain ::x ::y
    set x junk
    trace add variable ::x write [list foo $x]
    for {set y 0} {$y<100} {incr y} {
	catch {set x junk}
    }
    unset x
} __judge_r]
if {$__judge_c == 0 && $__judge_r eq {}} {puts PASS} else {puts "FAIL trace-8.8"}
# case: trace-9.1 cmd=unset
set __judge_c [catch {
    unset -nocomplain x
    set x 33
    set info {}
    trace add variable x unset {traceCheck {uplevel 1 set x}}
    unset x
    set info
} __judge_r]
if {$__judge_c == 0 && $__judge_r eq {1 {can't read "x": no such variable}}} {puts PASS} else {puts "FAIL trace-9.1"}
# case: trace-9.2 cmd=unset
set __judge_c [catch {
    unset -nocomplain x
    set x 33
    set info {}
    trace add variable x unset {traceCheck {uplevel 1 set x 22}}
    unset x
    concat $info [list [catch {set x} msg] $msg]
} __judge_r]
if {$__judge_c == 0 && $__judge_r eq {0 22 0 22}} {puts PASS} else {puts "FAIL trace-9.2"}
# case: trace-9.3 cmd=unset
set __judge_c [catch {
    unset -nocomplain x
    set x 33
    set info {}
    trace add variable x unset {traceCheck {uplevel 1 trace info variable x}}
    unset x
    set info
} __judge_r]
if {$__judge_c == 0 && $__judge_r eq {0 {}}} {puts PASS} else {puts "FAIL trace-9.3"}
# case: trace-9.4 cmd=unset
set __judge_c [catch {
    unset -nocomplain x
    set x 33
    set info {}
    trace add variable x unset {traceCheck {global x; trace add variable x unset traceProc}}
    unset x
    concat $info [trace info variable x]
} __judge_r]
if {$__judge_c == 0 && $__judge_r eq {0 {} {unset traceProc}}} {puts PASS} else {puts "FAIL trace-9.4"}
# case: trace-10.1 cmd=unset
set __judge_c [catch {
    unset -nocomplain x
    set x(0) 33
    set info {}
    trace add variable x(0) unset {traceCheck {uplevel 1 set x(0)}}
    unset x(0)
    set info
} __judge_r]
if {$__judge_c == 0 && $__judge_r eq {1 {can't read "x(0)": no such element in array}}} {puts PASS} else {puts "FAIL trace-10.1"}
# case: trace-10.2 cmd=unset
set __judge_c [catch {
    unset -nocomplain x
    set x(0) 33
    set info {}
    trace add variable x(0) unset {traceCheck {uplevel 1 set x(0) zzz}}
    unset x(0)
    concat $info [list [catch {set x(0)} msg] $msg]
} __judge_r]
if {$__judge_c == 0 && $__judge_r eq {0 zzz 0 zzz}} {puts PASS} else {puts "FAIL trace-10.2"}
# case: trace-10.3 cmd=unset
set __judge_c [catch {
    unset -nocomplain x
    set x(0) 33
    set info {}
    trace add variable x(0) unset {traceCheck {global x; trace info variable x(0)}}
    unset x(0)
    set info
} __judge_r]
if {$__judge_c == 0 && $__judge_r eq {0 {}}} {puts PASS} else {puts "FAIL trace-10.3"}
# case: trace-10.4 cmd=unset
set __judge_c [catch {
    unset -nocomplain x
    set x(0) 33
    set info {}
    trace add variable x(0) unset {traceCheck {uplevel 1 {trace add variable x(0) read {}}}}
    unset -nocomplain x(0)
    concat $info [trace info variable x(0)]
} __judge_r]
if {$__judge_c == 0 && $__judge_r eq {0 {} {read {}}}} {puts PASS} else {puts "FAIL trace-10.4"}
# case: trace-11.1 cmd=unset
set __judge_c [catch {
    unset -nocomplain x
    set x(0) 33
    set info {}
    trace add variable x unset {traceCheck {uplevel 1 set x(0)}}
    unset x
    set info
} __judge_r]
if {$__judge_c == 0 && $__judge_r eq {1 {can't read "x(0)": no such variable}}} {puts PASS} else {puts "FAIL trace-11.1"}
# case: trace-11.2 cmd=unset
set __judge_c [catch {
    unset -nocomplain x
    set x(y) 33
    set info {}
    trace add variable x unset {traceCheck {uplevel 1 set x(y) 22}}
    unset x
    concat $info [list [catch {set x(y)} msg] $msg]
} __judge_r]
if {$__judge_c == 0 && $__judge_r eq {0 22 0 22}} {puts PASS} else {puts "FAIL trace-11.2"}
# case: trace-11.3 cmd=unset
set __judge_c [catch {
    unset -nocomplain x
    set x(y) 33
    set info {}
    trace add variable x unset {traceCheck {uplevel 1 array exists x}}
    unset x
    set info
} __judge_r]
if {$__judge_c == 0 && $__judge_r eq {0 0}} {puts PASS} else {puts "FAIL trace-11.3"}
# case: trace-11.4 cmd=unset
set __judge_c [catch {
    unset -nocomplain x
    set x(y) 33
    set info {}
    set cmd {traceCheck {uplevel 1 {trace info variable x}}}
    trace add variable x unset $cmd
    unset x
    set info
} __judge_r]
if {$__judge_c == 0 && $__judge_r eq {0 {}}} {puts PASS} else {puts "FAIL trace-11.4"}
# case: trace-11.5 cmd=unset
set __judge_c [catch {
    unset -nocomplain x
    set x(y) 33
    set info {}
    trace add variable x unset {traceCheck {global x; trace add variable x read {}}}
    unset x
    concat $info [trace info variable x]
} __judge_r]
if {$__judge_c == 0 && $__judge_r eq {0 {} {read {}}}} {puts PASS} else {puts "FAIL trace-11.5"}
# case: trace-11.6 cmd=unset
set __judge_c [catch {
    unset -nocomplain x
    set x(y) 33
    set info {}
    trace add variable x unset {traceCheck {global x; set x 44}}
    unset x
    concat $info [list [catch {set x} msg] $msg]
} __judge_r]
if {$__judge_c == 0 && $__judge_r eq {0 44 0 44}} {puts PASS} else {puts "FAIL trace-11.6"}
# case: trace-12.1 cmd=unset
set __judge_c [catch {
    unset -nocomplain x
    set info {}
    trace add variable x(0) write traceProc
    list [catch {set x 22} msg] $msg
} __judge_r]
if {$__judge_c == 0 && $__judge_r eq {1 {can't set "x": variable is array}}} {puts PASS} else {puts "FAIL trace-12.1"}
# case: trace-12.2 cmd=unset
set __judge_c [catch {
    unset -nocomplain x
    set info {}
    trace add variable x(0) write traceProc
    list [catch {set x(0)} msg] $msg
} __judge_r]
if {$__judge_c == 0 && $__judge_r eq {1 {can't read "x(0)": no such element in array}}} {puts PASS} else {puts "FAIL trace-12.2"}
# case: trace-12.3 cmd=unset
set __judge_c [catch {
    unset -nocomplain x
    set info {}
    trace add variable x(0) write traceProc
    set x(0) 22
    set info
} __judge_r]
if {$__judge_c == 0 && $__judge_r eq {x 0 write}} {puts PASS} else {puts "FAIL trace-12.3"}
# case: trace-12.4 cmd=unset
set __judge_c [catch {
    unset -nocomplain x
    set info {}
    trace add variable x write traceProc
    list [catch {set x} msg] $msg
} __judge_r]
if {$__judge_c == 0 && $__judge_r eq {1 {can't read "x": no such variable}}} {puts PASS} else {puts "FAIL trace-12.4"}
# case: trace-12.5 cmd=unset
set __judge_c [catch {
    unset -nocomplain x
    set info {}
    trace add variable x write traceProc
    set x 22
    set info
} __judge_r]
if {$__judge_c == 0 && $__judge_r eq {x {} write}} {puts PASS} else {puts "FAIL trace-12.5"}
# case: trace-12.6 cmd=unset
set __judge_c [catch {
    unset -nocomplain x
    set info {}
    trace add variable x write traceProc
    set x(0) 22
    set info
} __judge_r]
if {$__judge_c == 0 && $__judge_r eq {x 0 write}} {puts PASS} else {puts "FAIL trace-12.6"}
# case: trace-12.7 cmd=unset
set __judge_c [catch {
    unset -nocomplain x
    set x(2) zzz
    trace add variable x read {traceCrtElement xyzzy}
    list [catch {set x(3)} msg] $msg
} __judge_r]
if {$__judge_c == 0 && $__judge_r eq {0 xyzzy}} {puts PASS} else {puts "FAIL trace-12.7"}
# case: trace-12.8 cmd=unset
set __judge_c [catch {
    unset -nocomplain x
    set x 44
    list [catch {trace add variable x(0) write traceProc} msg] $msg
} __judge_r]
if {$__judge_c == 0 && $__judge_r eq {1 {can't trace "x(0)": variable isn't array}}} {puts PASS} else {puts "FAIL trace-12.8"}
# case: trace-13.1 cmd=proc
set __judge_c [catch {
    proc delTraces {args} {
	global x
	trace remove variable x read {traceTag 2}
	trace remove variable x read {traceTag 3}
	trace remove variable x read {traceTag 4}
    }
    unset -nocomplain x
    set x 44
    set info {}
    trace add variable x read {traceTag 1}
    trace add variable x read {traceTag 2}
    trace add variable x read {traceTag 3}
    trace add variable x read {traceTag 4}
    trace add variable x read delTraces
    trace add variable x read {traceTag 5}
    set x
    set info
} __judge_r]
if {$__judge_c == 0 && $__judge_r eq {5 1}} {puts PASS} else {puts "FAIL trace-13.1"}
# case: trace-14.12 cmd=unset
set __judge_c [catch {
    unset -nocomplain x
    set info {}
    trace add variable x write traceProc
    trace remove variable x write traceProc
} __judge_r]
if {$__judge_c == 0 && $__judge_r eq {}} {puts PASS} else {puts "FAIL trace-14.12"}
# case: trace-14.13 cmd=unset
set __judge_c [catch {
    unset -nocomplain x
    set info {}
    trace add variable x write traceProc
    trace remove variable x write traceProc
    set x 12345
    set info
} __judge_r]
if {$__judge_c == 0 && $__judge_r eq {}} {puts PASS} else {puts "FAIL trace-14.13"}
# case: trace-14.14 cmd=unset
set __judge_c [catch {
    unset -nocomplain x
    set info {}
    trace add variable x write {traceTag 1}
    trace add variable x write traceProc
    trace add variable x write {traceTag 2}
    set x yy
    trace remove variable x write traceProc
    set x 12345
    trace remove variable x write {traceTag 1}
    set x foo
    trace remove variable x write {traceTag 2}
    set x gorp
    set info
} __judge_r]
if {$__judge_c == 0 && $__judge_r eq {2 x {} write 1 2 1 2}} {puts PASS} else {puts "FAIL trace-14.14"}
# case: trace-14.15 cmd=unset
set __judge_c [catch {
    unset -nocomplain x
    set info {}
    trace add variable x write {traceTag 1}
    trace remove variable x write non_existent
    set x 12345
    set info
} __judge_r]
if {$__judge_c == 0 && $__judge_r eq {1}} {puts PASS} else {puts "FAIL trace-14.15"}
# case: trace-14.16 cmd=unset
set __judge_c [catch {
    unset -nocomplain x
    trace add variable x write {traceTag 1}
    trace add variable x write traceProc
    trace add variable x write {traceTag 2}
    trace info variable x
} __judge_r]
if {$__judge_c == 0 && $__judge_r eq {{write {traceTag 2}} {write traceProc} {write {traceTag 1}}}} {puts PASS} else {puts "FAIL trace-14.16"}
# case: trace-14.17 cmd=unset
set __judge_c [catch {
    unset -nocomplain x
    trace info variable x
} __judge_r]
if {$__judge_c == 0 && $__judge_r eq {}} {puts PASS} else {puts "FAIL trace-14.17"}
# case: trace-14.18 cmd=unset
set __judge_c [catch {
    unset -nocomplain x
    trace info variable x(0)
} __judge_r]
if {$__judge_c == 0 && $__judge_r eq {}} {puts PASS} else {puts "FAIL trace-14.18"}
# case: trace-14.19 cmd=unset
set __judge_c [catch {
    unset -nocomplain x
    set x 44
    trace info variable x(0)
} __judge_r]
if {$__judge_c == 0 && $__judge_r eq {}} {puts PASS} else {puts "FAIL trace-14.19"}
# case: trace-14.20 cmd=unset
set __judge_c [catch {
    unset -nocomplain x
    set x 44
    trace add variable x write {traceTag 1}
    proc check {} {global x; trace info variable x}
    check
} __judge_r]
if {$__judge_c == 0 && $__judge_r eq {{write {traceTag 1}}}} {puts PASS} else {puts "FAIL trace-14.20"}
# case: trace-15.1 cmd=unset
set __judge_c [catch {
    unset -nocomplain x
    set info {}
    trace add variable x write {traceTag {This is a very very long argument.  It's \
	designed to test out the facilities of TraceVarProc for dealing \
	with such long arguments by malloc-ing space.  One possibility \
	is that space doesn't get freed properly.  If this happens, then \
	invoking this test over and over again will eventually leak memory.}}
    set x 44
    set info
} __judge_r]
if {$__judge_c == 0 && $__judge_r eq {This is a very very long argument.  It's \
	designed to test out the facilities of TraceVarProc for dealing \
	with such long arguments by malloc-ing space.  One possibility \
	is that space doesn't get freed properly.  If this happens, then \
	invoking this test over and over again will eventually leak memory.}} {puts PASS} else {puts "FAIL trace-15.1"}
# case: trace-15.2 cmd=proc
set __judge_c [catch {
    proc longResult {args} {return "quite a bit of text, designed to
	generate a core leak if this command file is invoked over and over again
	and memory isn't being recycled correctly"}
    unset -nocomplain x
    trace add variable x write longResult
    set x 44
    set x 5
    set x abcde
} __judge_r]
if {$__judge_c == 0 && $__judge_r eq {abcde}} {puts PASS} else {puts "FAIL trace-15.2"}
# case: trace-16.1 cmd=unset
set __judge_c [catch {
    unset -nocomplain y
    set y 1234
    set info {}
    trace add variable y read {traceUnset y}
    trace add variable y unset {traceAppend unset}
    lappend info [catch {set y} msg] $msg
} __judge_r]
if {$__judge_c == 0 && $__judge_r eq {unset 0 {} 1 {can't read "x": no such variable} 1 {can't read "y": no such variable}}} {puts PASS} else {puts "FAIL trace-16.1"}
# case: trace-16.2 cmd=unset
set __judge_c [catch {
    unset -nocomplain y
    set y(0) 1234
    set info {}
    trace add variable y(0) read {traceUnset y(0)}
    lappend info [catch {set y(0)} msg] $msg
} __judge_r]
if {$__judge_c == 0 && $__judge_r eq {0 {} 1 {can't read "x": no such variable} 1 {can't read "y(0)": no such element in array}}} {puts PASS} else {puts "FAIL trace-16.2"}
# case: trace-16.3 cmd=unset
set __judge_c [catch {
    unset -nocomplain y
    set y(0) 1234
    set info {}
    trace add variable y(0) read {traceUnset y}
    lappend info [catch {set y(0)} msg] $msg
} __judge_r]
if {$__judge_c == 0 && $__judge_r eq {0 {} 1 {can't read "x": no such variable} 1 {can't read "y(0)": no such variable}}} {puts PASS} else {puts "FAIL trace-16.3"}
# case: trace-16.4 cmd=unset
set __judge_c [catch {
    unset -nocomplain y
    set y 1234
    set info {}
    trace add variable y read {traceReset y y}
    lappend info [catch {set y} msg] $msg
} __judge_r]
if {$__judge_c == 0 && $__judge_r eq {0 {} 0 xyzzy 0 xyzzy}} {puts PASS} else {puts "FAIL trace-16.4"}
# case: trace-16.5 cmd=unset
set __judge_c [catch {
    unset -nocomplain y
    set y(0) 1234
    set info {}
    trace add variable y(0) read {traceReset y(0) y(0)}
    lappend info [catch {set y(0)} msg] $msg
} __judge_r]
if {$__judge_c == 0 && $__judge_r eq {0 {} 0 xyzzy 0 xyzzy}} {puts PASS} else {puts "FAIL trace-16.5"}
# case: trace-16.6 cmd=unset
set __judge_c [catch {
    unset -nocomplain y
    set y(0) 1234
    set info {}
    trace add variable y(0) read {traceReset y y(0)}
    lappend info [catch {set y(0)} msg] $msg [catch {set y(0)} msg] $msg
} __judge_r]
if {$__judge_c == 0 && $__judge_r eq {0 {} 1 {can't set "y": upvar refers to element in deleted array} 1 {can't read "y(0)": no such variable} 1 {can't read "y(0)": no such variable}}} {puts PASS} else {puts "FAIL trace-16.6"}
# case: trace-16.7 cmd=unset
set __judge_c [catch {
    unset -nocomplain y
    set y(0) 1234
    set info {}
    trace add variable y(0) read {traceReset2 y y(0)}
    lappend info [catch {set y(0)} msg] $msg [catch {set y(0)} msg] $msg
} __judge_r]
if {$__judge_c == 0 && $__judge_r eq {0 {} 0 xyzzy 1 {can't read "y(0)": no such element in array} 0 xyzzy}} {puts PASS} else {puts "FAIL trace-16.7"}
# case: trace-16.8 cmd=unset
set __judge_c [catch {
    unset -nocomplain y
    set y 1234
    set info {}
    trace add variable y write {traceUnset y}
    trace add variable y unset {traceAppend unset}
    lappend info [catch {set y xxx} msg] $msg
} __judge_r]
if {$__judge_c == 0 && $__judge_r eq {unset 0 {} 1 {can't read "x": no such variable} 0 {}}} {puts PASS} else {puts "FAIL trace-16.8"}
# case: trace-16.9 cmd=unset
set __judge_c [catch {
    unset -nocomplain y
    set y(0) 1234
    set info {}
    trace add variable y(0) write {traceUnset y(0)}
    lappend info [catch {set y(0) xxx} msg] $msg
} __judge_r]
if {$__judge_c == 0 && $__judge_r eq {0 {} 1 {can't read "x": no such variable} 0 {}}} {puts PASS} else {puts "FAIL trace-16.9"}
# case: trace-16.10 cmd=unset
set __judge_c [catch {
    unset -nocomplain y
    set y(0) 1234
    set info {}
    trace add variable y(0) write {traceUnset y}
    lappend info [catch {set y(0) xxx} msg] $msg
} __judge_r]
if {$__judge_c == 0 && $__judge_r eq {0 {} 1 {can't read "x": no such variable} 0 {}}} {puts PASS} else {puts "FAIL trace-16.10"}
# case: trace-16.11 cmd=unset
set __judge_c [catch {
    unset -nocomplain y
    set y 1234
    set info {}
    trace add variable y write {traceReset y y}
    lappend info [catch {set y xxx} msg] $msg
} __judge_r]
if {$__judge_c == 0 && $__judge_r eq {0 {} 0 xyzzy 0 xyzzy}} {puts PASS} else {puts "FAIL trace-16.11"}
# case: trace-16.12 cmd=unset
set __judge_c [catch {
    unset -nocomplain y
    set y(0) 1234
    set info {}
    trace add variable y(0) write {traceReset y(0) y(0)}
    lappend info [catch {set y(0) xxx} msg] $msg
} __judge_r]
if {$__judge_c == 0 && $__judge_r eq {0 {} 0 xyzzy 0 xyzzy}} {puts PASS} else {puts "FAIL trace-16.12"}
# case: trace-16.13 cmd=unset
set __judge_c [catch {
    unset -nocomplain y
    set y(0) 1234
    set info {}
    trace add variable y(0) write {traceReset y y(0)}
    lappend info [catch {set y(0) xxx} msg] $msg [catch {set y(0)} msg] $msg
} __judge_r]
if {$__judge_c == 0 && $__judge_r eq {0 {} 1 {can't set "y": upvar refers to element in deleted array} 0 {} 1 {can't read "y(0)": no such variable}}} {puts PASS} else {puts "FAIL trace-16.13"}
# case: trace-16.14 cmd=unset
set __judge_c [catch {
    unset -nocomplain y
    set y(0) 1234
    set info {}
    trace add variable y(0) write {traceReset2 y y(0)}
    lappend info [catch {set y(0) xxx} msg] $msg [catch {set y(0)} msg] $msg
} __judge_r]
if {$__judge_c == 0 && $__judge_r eq {0 {} 0 xyzzy 0 {} 0 xyzzy}} {puts PASS} else {puts "FAIL trace-16.14"}
# case: trace-16.15 cmd=unset
set __judge_c [catch {
    unset -nocomplain y
    set y 1234
    set info {}
    trace add variable y unset {traceUnset y}
    lappend info [catch {unset y} msg] $msg [catch {set y} msg] $msg
} __judge_r]
if {$__judge_c == 0 && $__judge_r eq {1 {can't unset "x": no such variable} 1 {can't read "x": no such variable} 0 {} 1 {can't read "y": no such variable}}} {puts PASS} else {puts "FAIL trace-16.15"}
# case: trace-16.16 cmd=unset
set __judge_c [catch {
    unset -nocomplain y
    set y(0) 1234
    set info {}
    trace add variable y(0) unset {traceUnset y(0)}
    lappend info [catch {unset y(0)} msg] $msg [catch {set y(0)} msg] $msg
} __judge_r]
if {$__judge_c == 0 && $__judge_r eq {1 {can't unset "x": no such variable} 1 {can't read "x": no such variable} 0 {} 1 {can't read "y(0)": no such element in array}}} {puts PASS} else {puts "FAIL trace-16.16"}
# case: trace-16.17 cmd=unset
set __judge_c [catch {
    unset -nocomplain y
    set y(0) 1234
    set info {}
    trace add variable y(0) unset {traceUnset y}
    lappend info [catch {unset y(0)} msg] $msg [catch {set y(0)} msg] $msg
} __judge_r]
if {$__judge_c == 0 && $__judge_r eq {0 {} 1 {can't read "x": no such variable} 0 {} 1 {can't read "y(0)": no such variable}}} {puts PASS} else {puts "FAIL trace-16.17"}
# case: trace-16.18 cmd=unset
set __judge_c [catch {
    unset -nocomplain y
    set y 1234
    set info {}
    trace add variable y unset {traceReset2 y y}
    lappend info [catch {unset y} msg] $msg [catch {set y} msg] $msg
} __judge_r]
if {$__judge_c == 0 && $__judge_r eq {1 {can't unset "y": no such variable} 0 xyzzy 0 {} 0 xyzzy}} {puts PASS} else {puts "FAIL trace-16.18"}
# case: trace-16.19 cmd=unset
set __judge_c [catch {
    unset -nocomplain y
    set y(0) 1234
    set info {}
    trace add variable y(0) unset {traceReset2 y(0) y(0)}
    lappend info [catch {unset y(0)} msg] $msg [catch {set y(0)} msg] $msg
} __judge_r]
if {$__judge_c == 0 && $__judge_r eq {1 {can't unset "y(0)": no such element in array} 0 xyzzy 0 {} 0 xyzzy}} {puts PASS} else {puts "FAIL trace-16.19"}
# case: trace-16.20 cmd=unset
set __judge_c [catch {
    unset -nocomplain y
    set y(0) 1234
    set info {}
    trace add variable y(0) unset {traceReset2 y y(0)}
    lappend info [catch {unset y(0)} msg] $msg [catch {set y(0)} msg] $msg
} __judge_r]
if {$__judge_c == 0 && $__judge_r eq {0 {} 0 xyzzy 0 {} 0 xyzzy}} {puts PASS} else {puts "FAIL trace-16.20"}
# case: trace-16.21 cmd=unset
set __judge_c [catch {
    unset -nocomplain y
    set y 1234
    set info {}
    trace add variable y read {traceAppend first}
    trace add variable y read {traceUnset y}
    trace add variable y read {traceAppend third}
    trace add variable y unset {traceAppend unset}
    lappend info [catch {set y} msg] $msg
} __judge_r]
if {$__judge_c == 0 && $__judge_r eq {third unset 0 {} 1 {can't read "x": no such variable} 1 {can't read "y": no such variable}}} {puts PASS} else {puts "FAIL trace-16.21"}
# case: trace-16.22 cmd=unset
set __judge_c [catch {
    unset -nocomplain y
    set y(0) 1234
    set info {}
    trace add variable y(0) read {traceAppend first}
    trace add variable y(0) read {traceUnset y}
    trace add variable y(0) read {traceAppend third}
    trace add variable y(0) unset {traceAppend unset}
    lappend info [catch {set y(0)} msg] $msg
} __judge_r]
if {$__judge_c == 0 && $__judge_r eq {third unset 0 {} 1 {can't read "x": no such variable} 1 {can't read "y(0)": no such variable}}} {puts PASS} else {puts "FAIL trace-16.22"}
# case: trace-17.1 cmd=unset
set __judge_c [catch {
    unset -nocomplain x
    set info {}
    trace add variable x unset {traceProc}
    list [catch {unset x} msg] $msg $info
} __judge_r]
if {$__judge_c == 0 && $__judge_r eq {1 {can't unset "x": no such variable} {x {} unset}}} {puts PASS} else {puts "FAIL trace-17.1"}
# case: trace-17.2 cmd=unset
set __judge_c [catch {
    unset -nocomplain x
    proc p1 {} {global x; trace add variable x write traceProc}
    p1
    trace info variable x
} __judge_r]
if {$__judge_c == 0 && $__judge_r eq {{write traceProc}}} {puts PASS} else {puts "FAIL trace-17.2"}
# case: trace-17.3 cmd=unset
set __judge_c [catch {
    unset -nocomplain x
    set info {}
    proc p1 {} {global x; trace add variable x write traceProc}
    p1
    set x 44
    set info
} __judge_r]
if {$__judge_c == 0 && $__judge_r eq {x {} write}} {puts PASS} else {puts "FAIL trace-17.3"}
# case: trace-18.1 cmd=proc
set __judge_c [catch {
    proc p1 {x y} {set a 44; p2 14}
    proc p2 {z} {trace add variable z unset {traceCheck {lsort [uplevel 1 {info vars}]}}}
    set info {}
    p1 foo bar
    set info
} __judge_r]
if {$__judge_c == 0 && $__judge_r eq {0 {a x y}}} {puts PASS} else {puts "FAIL trace-18.1"}
# case: trace-18.2 cmd=namespace
set __judge_c [catch {
    namespace eval ::foo {
	variable x 123
    }
    proc p1 args {
	trace remove variable ::foo::x unset p1
    }
    trace add variable ::foo::x unset p1
    namespace delete ::foo
    info exists ::foo::x
} __judge_r]
if {$__judge_c == 0 && $__judge_r eq {0}} {puts PASS} else {puts "FAIL trace-18.2"}
# case: trace-18.3 cmd=namespace
set __judge_c [catch {
    namespace eval ::ns {}
    trace add variable ::ns::var unset {unset ::ns::var ;#}
    namespace delete ::ns
} __judge_r]
if {$__judge_c == 0 && $__judge_r eq {}} {puts PASS} else {puts "FAIL trace-18.3"}
# case: trace-18.4 cmd=namespace
set __judge_c [catch {
    namespace eval ::ref {}
    set ::ref::var1 AAA
    trace add variable ::ref::var1 unset doTrace
    set ::ref::var2 BBB
    trace add variable ::ref::var2 {unset} doTrace
    proc doTrace {vtraced vidx op} {
	global info
	append info [catch {set ::$vtraced}][llength [info vars ::ref::*]]
    }
    set info {}
    namespace delete ::ref
    rename doTrace {}
    set info
} __judge_r]
if {$__judge_c == 0 && $__judge_r eq {1110}} {puts PASS} else {puts "FAIL trace-18.4"}
# case: trace-19.0.1 cmd=?
set __judge_c [catch {
    # Just in case!
    catch {rename nosuchname ""}
    list [catch {trace add command nosuchname rename traceCommand} msg] $msg
} __judge_r]
if {$__judge_c == 0 && $__judge_r eq {1 {unknown command "nosuchname"}}} {puts PASS} else {puts "FAIL trace-19.0.1"}
# case: trace-19.0.2 cmd=list
set __judge_c [catch {
    list [catch {trace add command nosuchns::nosuchname rename traceCommand} msg] $msg
} __judge_r]
if {$__judge_c == 0 && $__judge_r eq {1 {unknown command "nosuchns::nosuchname"}}} {puts PASS} else {puts "FAIL trace-19.0.2"}
# case: trace-19.1 cmd=proc
set __judge_c [catch {
    proc foo {} {}
    catch {rename bar {}}
    trace add command foo rename traceCommand
    rename foo bar
    set info
} __judge_r]
if {$__judge_c == 0 && $__judge_r eq {::foo ::bar rename}} {puts PASS} else {puts "FAIL trace-19.1"}
# case: trace-19.2 cmd=proc
set __judge_c [catch {
    proc foo {} {}
    catch {rename bar {}}
    trace add command foo rename traceCommand
    rename foo bar
    rename bar foo
    set info
} __judge_r]
if {$__judge_c == 0 && $__judge_r eq {::bar ::foo rename}} {puts PASS} else {puts "FAIL trace-19.2"}
# case: trace-19.2.1 cmd=proc
set __judge_c [catch {
    proc foo {} {}
    trace add command foo rename traceCommand
    trace info command foo
} __judge_r]
if {$__judge_c == 0 && $__judge_r eq {{rename traceCommand}}} {puts PASS} else {puts "FAIL trace-19.2.1"}
# case: trace-19.3 cmd=proc
set __judge_c [catch {
    proc foo {} {}
    set info {}
    trace add command foo rename traceCommand
    rename foo {}
    set info
} __judge_r]
if {$__judge_c == 0 && $__judge_r eq {}} {puts PASS} else {puts "FAIL trace-19.3"}
# case: trace-19.4 cmd=proc
set __judge_c [catch {
    proc foo {} {}
    catch {rename bar {}}
    set info {}
    trace add command foo rename traceCommand
    proc foo {} {}
    rename foo bar
    set info
} __judge_r]
if {$__judge_c == 0 && $__judge_r eq {}} {puts PASS} else {puts "FAIL trace-19.4"}
# case: trace-19.5 cmd=proc
set __judge_c [catch {
    proc foo {} {}
    trace add command foo rename traceCommand
    proc foo {} {}
    trace info command foo
} __judge_r]
if {$__judge_c == 0 && $__judge_r eq {}} {puts PASS} else {puts "FAIL trace-19.5"}
# case: trace-19.10 cmd=set
set __judge_c [catch {
    set info {}
    proc foo {} {}
    proc bar {} {}
    trace add command foo {rename delete} traceCommand
    catch {rename foo bar}
    set info
} __judge_r]
if {$__judge_c == 0 && $__judge_r eq {}} {puts PASS} else {puts "FAIL trace-19.10"}
# case: trace-20.1 cmd=trace
set __judge_c [catch {
    trace add command foo delete traceCommand
    rename foo ""
    set info
} __judge_r]
if {$__judge_c == 0 && $__judge_r eq {::foo {} delete}} {puts PASS} else {puts "FAIL trace-20.1"}
# case: trace-20.2 cmd=set
set __judge_c [catch {
    set info {}
    proc foo {} {}
    rename foo ""
    set info
} __judge_r]
if {$__judge_c == 0 && $__judge_r eq {}} {puts PASS} else {puts "FAIL trace-20.2"}
# case: trace-20.2.1 cmd=proc
set __judge_c [catch {
    proc foo {} {}
    trace add command foo delete traceCommand
    trace info command foo
} __judge_r]
if {$__judge_c == 0 && $__judge_r eq {{delete traceCommand}}} {puts PASS} else {puts "FAIL trace-20.2.1"}
# case: trace-20.3 cmd=proc
set __judge_c [catch {
    proc foo {} {}
    trace add command foo delete traceCommand
    proc foo {} {}
    set info
} __judge_r]
if {$__judge_c == 0 && $__judge_r eq {::foo {} delete}} {puts PASS} else {puts "FAIL trace-20.3"}
# case: trace-20.3.1 cmd=proc
set __judge_c [catch {
    proc foo {} {}
    trace info command foo
} __judge_r]
if {$__judge_c == 0 && $__judge_r eq {}} {puts PASS} else {puts "FAIL trace-20.3.1"}
# case: trace-20.4 cmd=set
set __judge_c [catch {
    set infotemp {}
    proc foo {} {}
    trace add command foo {rename delete} traceCommand
    rename foo bar
    lappend infotemp $info
    rename bar {}
    lappend infotemp $info
    set info $infotemp
    unset infotemp
    set info
} __judge_r]
if {$__judge_c == 0 && $__judge_r eq {{::foo ::bar rename} {::bar {} delete}}} {puts PASS} else {puts "FAIL trace-20.4"}
# case: trace-20.5 cmd=set
set __judge_c [catch {
    set infotemp {}
    set info {}
    proc foo {} {}
    trace add command foo {rename delete} traceCommand
    rename foo bar
    lappend infotemp $info
    rename bar {}
    lappend infotemp $info
    set info $infotemp
    unset infotemp
    set info
} __judge_r]
if {$__judge_c == 0 && $__judge_r eq {{::foo ::bar rename} {::bar {} delete}}} {puts PASS} else {puts "FAIL trace-20.5"}
# case: trace-20.8 cmd=set
set __judge_c [catch {
    set info {}
    proc foo {} {}
    catch {rename bar {}}
    trace add command foo {rename delete} [list traceDelete foo]
    rename foo bar
    list [set info] [trace info command bar]
} __judge_r]
if {$__judge_c == 0 && $__judge_r eq {{::foo ::bar rename} {}}} {puts PASS} else {puts "FAIL trace-20.8"}
# case: trace-20.9 cmd=set
set __judge_c [catch {
    set info {}
    proc foo {} {}
    catch {rename bar {}}
    catch {rename someothername {}}
    trace add command foo rename [list traceCmddelete foo]
    rename foo bar
    list [info commands foo] [info commands bar] [info commands someothername]
} __judge_r]
if {$__judge_c == 0 && $__judge_r eq {{} {} {}}} {puts PASS} else {puts "FAIL trace-20.9"}
# case: trace-20.10 cmd=set
set __judge_c [catch {
    set info {}
    proc foo {} {}
    catch {rename bar {}}
    catch {rename someothername {}}
    trace add command foo rename [list traceCmdrename foo]
    rename foo bar
    set info [list [info commands foo] [info commands bar] [info commands someothername]]
    rename someothername {}
    set info
} __judge_r]
if {$__judge_c == 0 && $__judge_r eq {{} {} someothername}} {puts PASS} else {puts "FAIL trace-20.10"}
# case: trace-20.11 cmd=set
set __judge_c [catch {
    set info {}
    proc foo {} {}
    catch {rename bar {}}
    catch {rename someothername {}}
    trace add command foo delete [list traceCmddelete foo]
    rename foo {}
    list [info commands foo] [info commands bar] [info commands someothername]
} __judge_r]
if {$__judge_c == 0 && $__judge_r eq {{} {} {}}} {puts PASS} else {puts "FAIL trace-20.11"}
# case: trace-20.12 cmd=set
set __judge_c [catch {
    set info {}
    proc foo {} {}
    catch {rename bar {}}
    catch {rename someothername {}}
    trace add command foo delete [list traceCmdrename foo]
    rename foo bar
    rename bar {}
    # None of these should exist.
    list [info commands foo] [info commands bar] [info commands someothername]
} __judge_r]
if {$__judge_c == 0 && $__judge_r eq {{} {} {}}} {puts PASS} else {puts "FAIL trace-20.12"}
# case: trace-20.13 cmd=proc
set __judge_c [catch {
    proc foo {} {}
    trace add command foo rename {set w Aha!;#}
    list [rename foo bar] [rename bar {}]
} __judge_r]
if {$__judge_c == 0 && $__judge_r eq {{} {}}} {puts PASS} else {puts "FAIL trace-20.13"}
# case: trace-20.14 cmd=proc
set __judge_c [catch {
    proc foo {} {}
    trace add command foo rename {error}
    list [rename foo bar] [rename bar {}]
} __judge_r]
if {$__judge_c == 0 && $__judge_r eq {{} {}}} {puts PASS} else {puts "FAIL trace-20.14"}
# case: trace-20.15 cmd=proc
set __judge_c [catch {
    proc foo {} {}
    trace add command foo delete {set w Aha!;#}
    rename foo {}
} __judge_r]
if {$__judge_c == 0 && $__judge_r eq {}} {puts PASS} else {puts "FAIL trace-20.15"}
# case: trace-20.16 cmd=proc
set __judge_c [catch {
    proc foo {} {}
    trace add command foo delete {error}
    rename foo {}
} __judge_r]
if {$__judge_c == 0 && $__judge_r eq {}} {puts PASS} else {puts "FAIL trace-20.16"}
# case: trace-21.1 cmd=set
set __judge_c [catch {
    set info {}
    trace add execution foo enter [list traceExecute foo]
    foo 1
    trace remove execution foo enter [list traceExecute foo]
    set info
} __judge_r]
if {$__judge_c == 0 && $__judge_r eq {{foo {foo 1} enter}}} {puts PASS} else {puts "FAIL trace-21.1"}
# case: trace-21.2 cmd=set
set __judge_c [catch {
    set info {}
    trace add execution foo leave [list traceExecute foo]
    foo 2
    trace remove execution foo leave [list traceExecute foo]
    set info
} __judge_r]
if {$__judge_c == 0 && $__judge_r eq {{foo {foo 2} 0 2 leave}}} {puts PASS} else {puts "FAIL trace-21.2"}
# case: trace-21.3 cmd=set
set __judge_c [catch {
    set info {}
    trace add execution foo {enter leave} [list traceExecute foo]
    foo 3
    trace remove execution foo {enter leave} [list traceExecute foo]
    set info
} __judge_r]
if {$__judge_c == 0 && $__judge_r eq {{foo {foo 3} enter} {foo {foo 3} 0 3 leave}}} {puts PASS} else {puts "FAIL trace-21.3"}
# case: trace-21.4 cmd=set
set __judge_c [catch {
    set info {}
    trace add execution foo {enter leave enterstep} [list traceExecute foo]
    foo 3
    trace remove execution foo {enter leave enterstep} [list traceExecute foo]
    set info
} __judge_r]
if {$__judge_c == 0 && $__judge_r eq {{foo {foo 3} enter} {foo {set b 3} enterstep} {foo {foo 3} 0 3 leave}}} {puts PASS} else {puts "FAIL trace-21.4"}
# case: trace-21.5 cmd=set
set __judge_c [catch {
    set info {}
    trace add execution foo {enter leave enterstep leavestep} [list traceExecute foo]
    foo 3
    trace remove execution foo {enter leave enterstep leavestep} [list traceExecute foo]
    set info
} __judge_r]
if {$__judge_c == 0 && $__judge_r eq {{foo {foo 3} enter} {foo {set b 3} enterstep} {foo {set b 3} 0 3 leavestep} {foo {foo 3} 0 3 leave}}} {puts PASS} else {puts "FAIL trace-21.5"}
# case: trace-21.6 cmd=set
set __judge_c [catch {
    set info {}
    trace add execution foo {enterstep leavestep} [list traceExecute foo]
    foo 3
    trace remove execution foo {enterstep leavestep} [list traceExecute foo]
    set info
} __judge_r]
if {$__judge_c == 0 && $__judge_r eq {{foo {set b 3} enterstep} {foo {set b 3} 0 3 leavestep}}} {puts PASS} else {puts "FAIL trace-21.6"}
# case: trace-21.7 cmd=set
set __judge_c [catch {
    set info {}
    trace add execution foo {enterstep} [list traceExecute foo]
    foo 3
    trace remove execution foo {enterstep} [list traceExecute foo]
    set info
} __judge_r]
if {$__judge_c == 0 && $__judge_r eq {{foo {set b 3} enterstep}}} {puts PASS} else {puts "FAIL trace-21.7"}
# case: trace-21.8 cmd=set
set __judge_c [catch {
    set info {}
    trace add execution foo {leavestep} [list traceExecute foo]
    foo 3
    trace remove execution foo {leavestep} [list traceExecute foo]
    set info
} __judge_r]
if {$__judge_c == 0 && $__judge_r eq {{foo {set b 3} 0 3 leavestep}}} {puts PASS} else {puts "FAIL trace-21.8"}
# case: trace-22.1 cmd=set
set __judge_c [catch {
    set info {}
    trace add execution factorial {enter} [list traceExecute factorial]
    factorial 1
    trace remove execution factorial {enter} [list traceExecute factorial]
    set info
} __judge_r]
if {$__judge_c == 0 && $__judge_r eq {{factorial {factorial 1} enter}}} {puts PASS} else {puts "FAIL trace-22.1"}
# case: trace-22.2 cmd=set
set __judge_c [catch {
    set info {}
    trace add execution factorial {enter} [list traceExecute factorial]
    factorial 2
    trace remove execution factorial {enter} [list traceExecute factorial]
    set info
} __judge_r]
if {$__judge_c == 0 && $__judge_r eq {{factorial {factorial 2} enter} {factorial {factorial 1} enter}}} {puts PASS} else {puts "FAIL trace-22.2"}
# case: trace-22.3 cmd=set
set __judge_c [catch {
    set info {}
    trace add execution factorial {enter} [list traceExecute factorial]
    factorial 3
    trace remove execution factorial {enter} [list traceExecute factorial]
    set info
} __judge_r]
if {$__judge_c == 0 && $__judge_r eq {{factorial {factorial 3} enter} {factorial {factorial 2} enter} {factorial {factorial 1} enter}}} {puts PASS} else {puts "FAIL trace-22.3"}
# case: trace-23.1 cmd=set
set __judge_c [catch {
    set info {}
    trace add execution factorial {enter leave enterstep leavestep} [list traceExecute]
    factorial 1
    trace remove execution factorial {enter leave enterstep leavestep} [list traceExecute]
    join $info "\n"
} __judge_r]
if {$__judge_c == 0 && $__judge_r eq {{factorial 1} enter
{if {$n != 1} { return [expr {$n * [factorial [expr {$n -1 }]]}] }} enterstep
{if {$n != 1} { return [expr {$n * [factorial [expr {$n -1 }]]}] }} 0 {} leavestep
{return 1} enterstep
{return 1} 2 1 leavestep
{factorial 1} 0 1 leave}} {puts PASS} else {puts "FAIL trace-23.1"}
# case: trace-23.2 cmd=set
set __judge_c [catch {
    set info {}
    trace add execution factorial {enter leave enterstep leavestep} [list traceExecute]
    factorial 2
    trace remove execution factorial {enter leave enterstep leavestep} [list traceExecute]
    join $info "\n"
} __judge_r]
if {$__judge_c == 0 && $__judge_r eq {{factorial 2} enter
{if {$n != 1} { return [expr {$n * [factorial [expr {$n -1 }]]}] }} enterstep
{expr {$n * [factorial [expr {$n -1 }]]}} enterstep
{expr {$n -1 }} enterstep
{expr {$n -1 }} 0 1 leavestep
{factorial 1} enterstep
{factorial 1} enter
{if {$n != 1} { return [expr {$n * [factorial [expr {$n -1 }]]}] }} enterstep
{if {$n != 1} { return [expr {$n * [factorial [expr {$n -1 }]]}] }} 0 {} leavestep
{return 1} enterstep
{return 1} 2 1 leavestep
{factorial 1} 0 1 leave
{factorial 1} 0 1 leavestep
{expr {$n * [factorial [expr {$n -1 }]]}} 0 2 leavestep
{return 2} enterstep
{return 2} 2 2 leavestep
{if {$n != 1} { return [expr {$n * [factorial [expr {$n -1 }]]}] }} 2 2 leavestep
{factorial 2} 0 2 leave}} {puts PASS} else {puts "FAIL trace-23.2"}
# case: trace-23.3 cmd=set
set __judge_c [catch {
    set info {}
    trace add execution factorial {enter leave enterstep leavestep} [list traceExecute]
    factorial 3
    trace remove execution factorial {enter leave enterstep leavestep} [list traceExecute]
    join $info "\n"
} __judge_r]
if {$__judge_c == 0 && $__judge_r eq {{factorial 3} enter
{if {$n != 1} { return [expr {$n * [factorial [expr {$n -1 }]]}] }} enterstep
{expr {$n * [factorial [expr {$n -1 }]]}} enterstep
{expr {$n -1 }} enterstep
{expr {$n -1 }} 0 2 leavestep
{factorial 2} enterstep
{factorial 2} enter
{if {$n != 1} { return [expr {$n * [factorial [expr {$n -1 }]]}] }} enterstep
{expr {$n * [factorial [expr {$n -1 }]]}} enterstep
{expr {$n -1 }} enterstep
{expr {$n -1 }} 0 1 leavestep
{factorial 1} enterstep
{factorial 1} enter
{if {$n != 1} { return [expr {$n * [factorial [expr {$n -1 }]]}] }} enterstep
{if {$n != 1} { return [expr {$n * [factorial [expr {$n -1 }]]}] }} 0 {} leavestep
{return 1} enterstep
{return 1} 2 1 leavestep
{factorial 1} 0 1 leave
{factorial 1} 0 1 leavestep
{expr {$n * [factorial [expr {$n -1 }]]}} 0 2 leavestep
{return 2} enterstep
{return 2} 2 2 leavestep
{if {$n != 1} { return [expr {$n * [factorial [expr {$n -1 }]]}] }} 2 2 leavestep
{factorial 2} 0 2 leave
{factorial 2} 0 2 leavestep
{expr {$n * [factorial [expr {$n -1 }]]}} 0 6 leavestep
{return 6} enterstep
{return 6} 2 6 leavestep
{if {$n != 1} { return [expr {$n * [factorial [expr {$n -1 }]]}] }} 2 6 leavestep
{factorial 3} 0 6 leave}} {puts PASS} else {puts "FAIL trace-23.3"}
# case: trace-24.1 cmd=set
set __judge_c [catch {
    set info {}
    trace add execution foo enter [list traceDelete foo]
    foo 1
    list $info [catch {trace info execution foo} res] $res
} __judge_r]
if {$__judge_c == 0 && $__judge_r eq {{{foo 1} enter} 0 {}}} {puts PASS} else {puts "FAIL trace-24.1"}
# case: trace-24.2 cmd=set
set __judge_c [catch {
    set info {}
    trace add execution foo leave [list traceDelete foo]
    foo 1
    list $info [catch {trace info execution foo} res] $res
} __judge_r]
if {$__judge_c == 0 && $__judge_r eq {{{foo 1} 0 1 leave} 0 {}}} {puts PASS} else {puts "FAIL trace-24.2"}
# case: trace-24.3 cmd=set
set __judge_c [catch {
    set info {}
    trace add execution foo {enter leave} [list traceDelete foo]
    foo 1
    list $info [catch {trace info execution foo} res] $res
} __judge_r]
if {$__judge_c == 0 && $__judge_r eq {{{foo 1} enter} 0 {}}} {puts PASS} else {puts "FAIL trace-24.3"}
# case: trace-24.4 cmd=set
set __judge_c [catch {
    set info {}
    trace add execution foo {enter leave enterstep leavestep} [list traceDelete foo]
    foo 1
    list $info [catch {trace info execution foo} res] $res
} __judge_r]
if {$__judge_c == 0 && $__judge_r eq {{{foo 1} enter} 0 {}}} {puts PASS} else {puts "FAIL trace-24.4"}
# case: trace-24.5 cmd=set
set __judge_c [catch {
    set info {}
    trace add execution foo {leave enterstep leavestep} [list traceDelete foo]
    foo 1
    list $info [catch {trace info execution foo} res] $res
} __judge_r]
if {$__judge_c == 0 && $__judge_r eq {{{set b 1} enterstep} 0 {}}} {puts PASS} else {puts "FAIL trace-24.5"}
# case: trace-25.1 cmd=set
set __judge_c [catch {
    set info {}
    trace add execution foo enter [list traceDelete foo]
    catch {foo 1} err
    list $err $info [catch {trace info execution foo} res] $res
} __judge_r]
if {$__judge_c == 0 && $__judge_r eq {{invalid command name "foo"} {{foo 1} enter} 1 {unknown command "foo"}}} {puts PASS} else {puts "FAIL trace-25.1"}
# case: trace-25.2 cmd=set
set __judge_c [catch {
    set info {}
    trace add execution foo leave [list traceDelete foo]
    foo 1
    list $info [catch {trace info execution foo} res] $res
} __judge_r]
if {$__judge_c == 0 && $__judge_r eq {{{foo 1} 0 1 leave} 1 {unknown command "foo"}}} {puts PASS} else {puts "FAIL trace-25.2"}
# case: trace-25.3 cmd=set
set __judge_c [catch {
    set info {}
    trace add execution foo enter [list traceDelete foo]
    trace add execution foo leave [list traceDelete foo]
    catch {foo 1} err
    list $err $info [catch {trace info execution foo} res] $res
} __judge_r]
if {$__judge_c == 0 && $__judge_r eq {{invalid command name "foo"} {{foo 1} enter} 1 {unknown command "foo"}}} {puts PASS} else {puts "FAIL trace-25.3"}
# case: trace-25.4 cmd=set
set __judge_c [catch {
    set info {}
    trace add execution foo enter [list traceExecute traceExecute]
    trace add execution foo enter [list traceExecute2 traceExecute2]
    catch {foo 1} err
    trace remove execution foo enter [list traceExecute traceExecute]
    trace remove execution foo enter [list traceExecute2 traceExecute2]
    join [list $err [join $info \n] [trace info execution foo]] "\n"
} __judge_r]
if {$__judge_c == 0 && $__judge_r eq {1
traceExecute2 {foo 1} enter
traceExecute {foo 1} enter
}} {puts PASS} else {puts "FAIL trace-25.4"}
# case: trace-25.5 cmd=set
set __judge_c [catch {
    set info {}
    trace add execution foo enterstep [list traceExecute traceExecute]
    trace add execution foo enterstep [list traceExecute2 traceExecute2]
    catch {foo 1} err
    trace remove execution foo enterstep [list traceExecute traceExecute]
    trace remove execution foo enterstep [list traceExecute2 traceExecute2]
    join [list $err [join $info \n] [trace info execution foo]] "\n"
} __judge_r]
if {$__judge_c == 0 && $__judge_r eq {1
traceExecute2 {set b 1} enterstep
traceExecute {set b 1} enterstep
}} {puts PASS} else {puts "FAIL trace-25.5"}
# case: trace-25.6 cmd=set
set __judge_c [catch {
    set info {}
    trace add execution foo leave [list tracePostExecute tracePostExecute]
    trace add execution foo leave [list tracePostExecute2 tracePostExecute2]
    catch {foo 1} err
    trace remove execution foo leave [list tracePostExecute tracePostExecute]
    trace remove execution foo leave [list tracePostExecute2 tracePostExecute2]
    join [list $err [join $info \n] [trace info execution foo]] "\n"
} __judge_r]
if {$__judge_c == 0 && $__judge_r eq {1
tracePostExecute {foo 1} 0 leave
tracePostExecute2 {foo 1} 0 leave
}} {puts PASS} else {puts "FAIL trace-25.6"}
# case: trace-25.7 cmd=set
set __judge_c [catch {
    set info {}
    trace add execution foo leavestep [list tracePostExecute tracePostExecute]
    trace add execution foo leavestep [list tracePostExecute2 tracePostExecute2]
    catch {foo 1} err
    trace remove execution foo leavestep [list tracePostExecute tracePostExecute]
    trace remove execution foo leavestep [list tracePostExecute2 tracePostExecute2]
    join [list $err [join $info \n] [trace info execution foo]] "\n"
} __judge_r]
if {$__judge_c == 0 && $__judge_r eq {1
tracePostExecute {set b 1} 0 leavestep
tracePostExecute2 {set b 1} 0 leavestep
}} {puts PASS} else {puts "FAIL trace-25.7"}
# case: trace-25.8 cmd=set
set __judge_c [catch {
    set info {}
    trace add execution foo enter [list traceDelete foo]
    trace add execution foo leave [list traceDelete foo]
    trace add execution foo enterstep [list traceDelete foo]
    trace add execution foo leavestep [list traceDelete foo]
    catch {foo 1} err
    list $err $info [catch {trace info execution foo} res] $res
} __judge_r]
if {$__judge_c == 0 && $__judge_r eq {{invalid command name "foo"} {{foo 1} enter} 1 {unknown command "foo"}}} {puts PASS} else {puts "FAIL trace-25.8"}
# case: trace-25.9 cmd=set
set __judge_c [catch {
    set info {}
    trace add execution foo enter [list traceDelete foo]
    trace add execution foo leave [list traceDelete foo]
    trace add execution foo leavestep [list traceDelete foo]
    catch {foo 1} err
    list $err $info [catch {trace info execution foo} res] $res
} __judge_r]
if {$__judge_c == 0 && $__judge_r eq {{invalid command name "foo"} {{foo 1} enter} 1 {unknown command "foo"}}} {puts PASS} else {puts "FAIL trace-25.9"}
# case: trace-25.10 cmd=set
set __judge_c [catch {
    set info {}
    trace add execution foo leave [list traceDelete foo]
    trace add execution foo leavestep [list traceDelete foo]
    catch {foo 1} err
    list $err $info [catch {trace info execution foo} res] $res
} __judge_r]
if {$__judge_c == 0 && $__judge_r eq {1 {{set b 1} 0 1 leavestep} 1 {unknown command "foo"}}} {puts PASS} else {puts "FAIL trace-25.10"}
# case: trace-25.11 cmd=set
set __judge_c [catch {
    set info {}
    trace add execution foo enter [list traceDelete foo]
    trace add execution foo enterstep [list traceDelete foo]
    catch {foo 1} err
    list $err $info [catch {trace info execution foo} res] $res
} __judge_r]
if {$__judge_c == 0 && $__judge_r eq {{invalid command name "foo"} {{foo 1} enter} 1 {unknown command "foo"}}} {puts PASS} else {puts "FAIL trace-25.11"}
# case: trace-27.1 cmd=catch
set __judge_c [catch {
    catch {rename bar {}}
    proc foo {} {error foo}
    trace add command foo rename {rename foo "" ;#}
    rename foo bar
    info commands foo
} __judge_r]
if {$__judge_c == 0 && $__judge_r eq {}} {puts PASS} else {puts "FAIL trace-27.1"}
# case: trace-27.2 cmd=list
set __judge_c [catch {
    list [catch {trace remove command thisdoesntexist \
      {delete rename} bar} res] $res
} __judge_r]
if {$__judge_c == 0 && $__judge_r eq {1 {unknown command "thisdoesntexist"}}} {puts PASS} else {puts "FAIL trace-27.2"}
# case: trace-27.3 cmd=list
set __judge_c [catch {
    list [catch {trace info command thisdoesntexist} res] $res
} __judge_r]
if {$__judge_c == 0 && $__judge_r eq {1 {unknown command "thisdoesntexist"}}} {puts PASS} else {puts "FAIL trace-27.3"}
# case: trace-28.2 cmd=set
set __judge_c [catch {
    set info {}
    set res {}

    proc foo {} {
	if {[catch {bar}]} {
	    return "error"
	} else {
	    return "ok"
	}
    }

    proc bar {} { error "msg" }

    lappend res [foo]

    trace add execution foo {enter enterstep leave leavestep} \
      [list traceExecute foo]

    # With the trace active

    lappend res [foo]

    trace remove execution foo {enter enterstep leave leavestep} \
      [list traceExecute foo]

    list $res [join $info \n]
} __judge_r]
if {$__judge_c == 0 && $__judge_r eq {{error error} {foo foo enter
foo {if {[catch {bar}]} {
	    return "error"
	} else {
	    return "ok"
	}} enterstep
foo {catch bar} enterstep
foo bar enterstep
foo {error msg} enterstep
foo {error msg} 1 msg leavestep
foo bar 1 msg leavestep
foo {catch bar} 0 1 leavestep
foo {return error} enterstep
foo {return error} 2 error leavestep
foo {if {[catch {bar}]} {
	    return "error"
	} else {
	    return "ok"
	}} 2 error leavestep
foo foo 0 error leave}}} {puts PASS} else {puts "FAIL trace-28.2"}
# case: trace-28.3 cmd=set
set __judge_c [catch {
    set info {}
    set res {}

    proc foo {} {
	if {[catch {bar}]} {
	    return "error"
	} else {
	    return "ok"
	}
    }

    proc bar {} { return -code error "msg" }

    lappend res [foo]

    trace add execution foo {enter enterstep leave leavestep} \
      [list traceExecute foo]

    # With the trace active

    lappend res [foo]

    trace remove execution foo {enter enterstep leave leavestep} \
      [list traceExecute foo]

    list $res [join $info \n]
} __judge_r]
if {$__judge_c == 0 && $__judge_r eq {{error error} {foo foo enter
foo {if {[catch {bar}]} {
	    return "error"
	} else {
	    return "ok"
	}} enterstep
foo {catch bar} enterstep
foo bar enterstep
foo {return -code error msg} enterstep
foo {return -code error msg} 2 msg leavestep
foo bar 1 msg leavestep
foo {catch bar} 0 1 leavestep
foo {return error} enterstep
foo {return error} 2 error leavestep
foo {if {[catch {bar}]} {
	    return "error"
	} else {
	    return "ok"
	}} 2 error leavestep
foo foo 0 error leave}}} {puts PASS} else {puts "FAIL trace-28.3"}
# case: trace-28.6 cmd=set
set __judge_c [catch {
    set info {}
    proc enterStep {cmd op} {lappend ::info "enter $cmd/$op"}
    proc leaveStep {cmd code result op} {lappend ::info "leave $cmd/$code/$result/$op"}

    proc foo x {
	set b x=$x
	incr x
    }
    trace add execution foo enterstep enterStep
    trace add execution foo leavestep leaveStep
    foo 42
    rename foo {}
    join $info \n
} __judge_r]
if {$__judge_c == 0 && $__judge_r eq {enter set b x=42/enterstep
leave set b x=42/0/x=42/leavestep
enter incr x/enterstep
leave incr x/0/43/leavestep}} {puts PASS} else {puts "FAIL trace-28.6"}
# case: trace-28.7 cmd=set
set __judge_c [catch {
    set info {}
    proc foo x { incr x }
    proc bar {args} {}
    trace add execution foo {enter leave enterstep leavestep} bar
    set info [trace info execution foo]
    trace remove execution foo {enter leave enterstep leavestep} bar
} __judge_r]
if {$__judge_c == 0 && $__judge_r eq {}} {puts PASS} else {puts "FAIL trace-28.7"}
# case: trace-28.8 cmd=list
set __judge_c [catch {
    list [catch {trace remove execution thisdoesntexist \
      {enter leave enterstep leavestep} bar} res] $res
} __judge_r]
if {$__judge_c == 0 && $__judge_r eq {1 {unknown command "thisdoesntexist"}}} {puts PASS} else {puts "FAIL trace-28.8"}
# case: trace-28.9 cmd=list
set __judge_c [catch {
    list [catch {trace info execution thisdoesntexist} res] $res
} __judge_r]
if {$__judge_c == 0 && $__judge_r eq {1 {unknown command "thisdoesntexist"}}} {puts PASS} else {puts "FAIL trace-28.9"}
# case: trace-28.10 cmd=list
set __judge_c [catch {
    list [catch {trace remove execution} res] $res
} __judge_r]
if {$__judge_c == 0 && $__judge_r eq {1 {wrong # args: should be "trace remove execution name opList command"}}} {puts PASS} else {puts "FAIL trace-28.10"}
# case: trace-33.1 cmd=unset
set __judge_c [catch {
    unset -nocomplain x
    trace add variable x write foo
    trace remove variable x write foo
    llength [trace info variable x]
} __judge_r]
if {$__judge_c == 0 && $__judge_r eq {0}} {puts PASS} else {puts "FAIL trace-33.1"}
# case: trace-34.1 cmd=set
set __judge_c [catch {
    set ::x [list]
    proc foo {} {lappend ::x foo}
    proc bar args {
	lappend ::x $args
	trace remove execution foo leavestep bar
	trace remove execution foo enterstep bar
	trace add execution foo leavestep bar
	trace add execution foo enterstep bar
	lappend ::x done
    }
    trace add execution foo leavestep bar
    trace add execution foo enterstep bar
    foo
    set ::x
} __judge_r]
if {$__judge_c == 0 && $__judge_r eq {{{lappend ::x foo} enterstep} done foo}} {puts PASS} else {puts "FAIL trace-34.1"}
# case: trace-34.2 cmd=proc
set __judge_c [catch {
    proc foo {} {}
    proc bar args {trace remove execution foo leave soom}
    trace add execution foo leave bar
    trace add execution foo leave soom
    foo
} __judge_r]
if {$__judge_c == 0 && $__judge_r eq {}} {puts PASS} else {puts "FAIL trace-34.2"}
# case: trace-34.3 cmd=proc
set __judge_c [catch {
    proc foo {} {set x {}}
    proc bar args {trace remove execution foo enterstep soom}
    trace add execution foo enterstep soom
    trace add execution foo enterstep bar
    foo
} __judge_r]
if {$__judge_c == 0 && $__judge_r eq {}} {puts PASS} else {puts "FAIL trace-34.3"}
# case: trace-34.4 cmd=variable
set __judge_c [catch {
    variable x notrace
    proc callback {old - -} {
	variable x "$old exists: [namespace which -command $old]"
    }
    namespace eval ::foo {proc bar {} {}}
    trace add command ::foo::bar delete [namespace code callback]
    namespace delete ::foo
    set x
} __judge_r]
if {$__judge_c == 0 && $__judge_r eq {::foo::bar exists: ::foo::bar}} {puts PASS} else {puts "FAIL trace-34.4"}
# case: trace-34.5 cmd=variable
set __judge_c [catch {
    variable x notrace
    proc callback {old - -} {
	variable x "$old exists: [namespace which -command $old]"
    }
    namespace eval ::foo {proc bar {} {}}
    trace add command ::foo::bar delete [namespace code callback]
    namespace eval ::foo namespace delete ::foo
    set x
} __judge_r]
if {$__judge_c == 0 && $__judge_r eq {::foo::bar exists: }} {puts PASS} else {puts "FAIL trace-34.5"}
# case: trace-40.1 cmd=proc
set __judge_c [catch {
    proc foo args {}
    trace add execution foo enter {rename foo {}; error bar;#}
    catch foo m
    return -level 0 $m[unset m]
} __judge_r]
if {$__judge_c == 0 && $__judge_r eq {bar}} {puts PASS} else {puts "FAIL trace-40.1"}
