catch {format %*d x 3} m; puts "8.9: [catch {set m} e]; $m"
catch {format %*.*f 2 xyz 3} m; puts "8.10: $m"
catch {format %d 2a} m; puts "8.11: code=$m err=$::errorCode"
catch {format %c 2x} m; puts "8.13: $m"
catch {format ab%} m; puts "8.17: $m"
catch {format ab% 12} m; puts "8.18: $m"
catch {format %q x} m; puts "8.19: $m"
catch {format %r x} m; puts "8.20: $m"
catch {format "%d %d" 24 xyz} m; puts "8.23: $m"
