catch {string is a x} m; puts "ambig: $m"
catch {string is al x} m; puts "ambig2: $m"
puts "int -5: [string is integer -5]"
puts "int -strict -5: [string is integer -strict -5]"
catch {string is integer -- -5} m; puts "dashdash: $m"
catch {string is digit -failindex p} m; puts "nofailstr: $m"
puts "failidx then strict: [string is digit -failindex pp -strict 12a]; pp=$pp"
puts "double { 1.5 }: [string is double { 1.5 }]"
puts "double 0b101: [string is double 0b101]"
puts "double 010: [string is double 010]"
puts "double 1,5: [string is double 1,5]"
puts "integer { }: [string is integer { }]"
puts "double inf: [string is double inf] infinity: [string is double infinity]"
puts "totitle hELLOwORLD 6: [string totitle hELLOwORLD 6]"
puts "totitle hELLO 1 3: [string totitle hELLO 1 3]"
puts "is digit failindex on mixed: [string is digit -failindex q 1²3]; q=$q"
catch {string is digit -failindex} m; puts "failnoval: $m"
puts "class abbrev f: [catch {string is f 0} m]; $m"
puts "class abbrev t: [catch {string is t 1} m]; $m"
puts "class abbrev w: [catch {string is w a} m]; $m"
puts "class abbrev s: [catch {string is s { }} m]; $m"
puts "class abbrev wi: [catch {string is wi 5} m]; $m"
puts "class abbrev e: [catch {string is e 5} m]; $m"
puts "class abbrev d: [catch {string is d 5} m]; $m"
puts "class abbrev b: [catch {string is b 1} m]; $m"
puts "class abbrev l: [catch {string is l {}} m]; $m"
puts "class abbrev p: [catch {string is p !} m]; $m"
puts "class abbrev u: [catch {string is u A} m]; $m"
puts "class abbrev g: [catch {string is g !} m]; $m"
puts "class abbrev x: [catch {string is x F} m]; $m"
puts "class abbrev c: [catch {string is c \t} m]; $m"
