puts "totitle ABCDEF 2: [string totitle ABCDEF 2]"
puts "totitle ABCDEF 2 3: [string totitle ABCDEF 2 3]"
puts "totitle ABCDEF: [string totitle ABCDEF]"
puts "totitle abcdef 2: [string totitle abcdef 2]"
puts "totitle abcdef 2 3: [string totitle abcdef 2 3]"
puts "toupper ABCDEF 9: <[string toupper ABCDEF 9]>"
puts "toupper ABCDEF -1: <[string toupper ABCDEF -1]>"
puts "toupper ABCDEF end: <[string toupper ABCDEF end]>"
puts "toupper ABCDEF 2 end+5: <[string toupper ABCDEF 2 end+5]>"
puts "tolower abc -strict?: [catch {string tolower abc -strict} m]; $m"
