puts "len(𝟘)=[string length 𝟘]"
puts "len(é)=[string length é]"
set s 𝟘ab
puts "index of a in 𝟘ab: [string first a $s]"
puts "is digit 𝟘: [string is digit 𝟘]"
puts "toupper ᴀ (U+1D00): [string toupper ᴀ] cp=[format U+%04X [scan [string toupper ᴀ] %c]]"
puts "toupper 𝟘 unchanged? [string toupper 𝟘]"
puts "is digit -failindex on empty:"
puts [string is digit -failindex p3 {}]
puts "p3 exists? [info exists p3]"
puts [string is digit -strict -failindex p4 {}]
puts "p4 exists? [info exists p4] val=[expr {[info exists p4] ? $p4 : {n/a}}]"
puts [string is digit -failindex p5 12a34]
puts "p5=$p5"
catch {string foo bar} m; puts "A: $m"
catch {string tolower} m; puts "B: $m"
catch {string toupper a b} m; puts "C: $m"
catch {string trim a b c d} m; puts "D: $m"
catch {string match} m; puts "E: $m"
catch {string map abc x} m; puts "F: $m"
catch {string map {a b c} x} m; puts "G: $m"
catch {string repeat a} m; puts "H: $m"
catch {string repeat a x} m; puts "I: $m"
catch {string first a} m; puts "J: $m"
catch {string replace a 1} m; puts "K: $m"
catch {string index a} m; puts "L: $m"
catch {string range a 1} m; puts "M: $m"
catch {string equal a} m; puts "N: $m"
catch {string equal -bogus a b} m; puts "O: $m"
catch {string equal -length x a b} m; puts "P: $m"
catch {string compare -length -3 ab cd} m; puts "Q: $m"
catch {string bytelength} m; puts "R: $m"
catch {string cat} m; puts "S: <$m>"
catch {string wordstart a} m; puts "T: $m"
catch {string wordend a b c} m; puts "U: $m"
catch {string last a} m; puts "V: $m"
catch {string reverse a b} m; puts "W: $m"
catch {string totitle a b} m; puts "X: $m"
catch {string trimleft} m; puts "Y: $m"
catch {string byterange a 1} m; puts "Z: $m"
