puts [list "a}b"]
puts [list "a b"]
puts [list "a\nb"]
puts [list ""]
puts [list "\\"]
puts [list "a\$b"]
puts [list "a{b"]
puts [list "a{b}c"]
puts [list "a{b}c{d"]
puts [list "a\"b"]
puts [list "a;b"]
puts [list "a\tb"]
puts [list "a\[b"]
puts [list "a\]b"]
puts [list "a\\\tb"]
puts [list "{"]
puts [list "}"]
puts [list "a b" "" "c\nd"]
puts [list "\x01\x02"]
puts [list "a{b}\u0041"]
puts [list "\\n"]
puts [list "a\\nb"]
puts [list "x{y}z"]
puts [list " "]
puts [list "\u00e9"]
