puts "E9a:[catch {set x foo; while {$x} {set x 0}} m]; $m"
puts "E5:[expr {010}]"
puts "E7:[catch {expr {abc}} m]; $m"
puts "E10:[catch {expr {1 | 2.5}} m]; $m"
puts "E11:[catch {expr {1 >> -1}} m]; $m"
puts "E12:[catch {expr {"a" in "{"}} m]; $m"
puts "L4:[catch {lsort -integer {a 1}} m]; $m"
puts "L5:[lsort -unique -nocase {a A b}]"
puts "V3:[proc f args {return $args}; f \"a}b\" c]"
puts "V6:[catch {uplevel 1 {set q 9}} m]; $m"
puts "C3:[catch {list a} r o]; $o"
puts "C6:[proc g {} {return -code return inner}; catch {g} m]; $m"
