puts "wordchar _: [string is wordchar _]"
puts "wordchar é: [string is wordchar é]"
puts "wordchar 5: [string is wordchar 5]"
puts "wordchar ‿ U+203F: [string is wordchar ‿]"
puts "wordchar ー U+30FC: [string is wordchar ー]"
puts "entier 0x10: [string is entier 0x10]"
puts "entier 1e3: [string is entier 1e3]"
puts "integer 1e3: [string is integer 1e3]"
puts "true yes: [string is true yes]"
puts "true 0: [string is true 0]"
puts "true 2: [string is true 2]"
puts "false no: [string is false no]"
puts "false 2: [string is false 2]"
puts "boolean 2: [string is boolean 2]"
catch {string is dig 5} m; puts "abbr: $m"
catch {string is int 5} m; puts "int alias: $m"
puts "toupper hello 1 3: [string toupper hello 1 3]"
puts "toupper hello 2: [string toupper hello 2]"
puts "toupper hello 0 end: [string toupper hello 0 end]"
puts "toupper hello 3 1: <[string toupper hello 3 1]>"
puts "toupper hello 9: <[string toupper hello 9]>"
catch {string toupper hello x} m; puts "badidx: $m"
puts "tolower ABCDEF 1 end-2: [string tolower ABCDEF 1 end-2]"
puts "totitle hello world 6: [string totitle {hello world} 6]"
puts "double .5: [string is double .5], double 0x10: [string is double 0x10], double Inf: [string is double Inf], double NaN: [string is double NaN], double 1e: [string is double 1e], double { }: <[string is double { }]>"
puts "integer {42 }: [string is integer {42 }]"
puts "ascii é: [string is ascii é]"
puts "is list -strict {: [string is list -strict \{]"
