puts [string first y héy]
puts [string first y héy 2]
puts [string first y héy 3]
puts [string first {} abc]
puts [string first {} abc 2]
puts [string first a abc 9]
puts [string first y héy end]
puts [string first c abc 3]
puts [string first c abc end-1]
puts [string first a abc -1]
puts [string last y héyéy]
puts [string last y héyéy 2]
puts [string last {} abc]
puts [string last b abcabc 1]
puts [string last abc abcabc 0]
puts [string last abc abcabc 2]
puts [string last c abcabc end]
puts [string last bc abcabc 1]
puts [string last bc abcabc 3]
puts [string last a abc -1]
puts [string index héy 1]
puts [string range héy 1 end]
puts [string totitle {hello world}]
puts [string totitle {hELLO wORLD}]
puts "<[string totitle {}]>"
puts [string totitle ünïcodé]
puts "<[string repeat ab -1]>"
puts "<[string repeat ab 0]>"
puts [string repeat ab 3]
puts [string is boolean tru]
puts [string is boolean t]
puts [string is boolean trx]
puts [string is boolean o]
puts [string is boolean f]
puts [string is boolean y]
puts [string is boolean 2]
puts [string is boolean 1]
puts [string is boolean OFF]
puts [string is boolean -strict tru]
puts [string is integer " 42"]
puts [string is integer 0x10]
puts [string is integer +42]
puts [string is integer -strict " 42"]
puts [string is integer 010]
puts [string is integer 0b101]
puts [string is integer "42 "]
puts [string is integer -0x10]
puts [string is integer -strict 0x10]
puts [string is integer "  "]
puts [string is integer 08]
puts [string is integer 0o17]
puts [string is integer 0b2]
puts [string is integer 0x]
puts [string is integer +]
puts [string is integer 00]
puts [string is integer 0]
puts [string is integer -010]
puts [string is integer 0X10]
puts [string is integer 0B11]
puts [string is integer 99999999999999999999999999]
puts [string is wideinteger 0x10]
puts [string is wideinteger 99999999999999999999999999]
